name: gasox
description: GASOX - Detector de Humo con ESP32

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4
  wifi_scan: ^0.4.1
  network_info_plus: ^6.1.4
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_local_notifications: ^19.2.1
  workmanager: ^0.6.0
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.6
  multicast_dns: ^0.3.3
  audioplayers: ^5.2.1
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700